s3_grandprix_result_data_key:
  "race_result": "data/race_result.csv"
  "fastest_lap": "data/fastest_lap.csv"
  "grid": "data/grid.csv"
  "qualify": "data/qualify.csv"
  "pit_stop": "data/pit_stop.csv"
  "sprint": "data/sprint.csv"

constructor_mapping:
  "Red Bull Renault": "Red Bull"
  "STR Ferrari": "Red Bull Junior Team"
  "Red Bull Racing Renault": "Red Bull"
  "Lotus Renault": "Lotus"
  "Lotus Mercedes": "Lotus"
  "Red Bull Racing TAG Heuer": "Red Bull"
  "Toro Rosso Ferrari": "Red Bull Junior Team"
  "Toro Rosso": "Red Bull Junior Team"
  "Scuderia Toro Rosso Honda": "Red Bull Junior Team"
  "AlphaTauri Honda": "Red Bull Junior Team"
  "AlphaTauri RBPT": "Red Bull Junior Team"
  "Red Bull Racing RBPT": "Red Bull"
  "Red Bull Racing Honda RBPT": "Red Bull"
  "McLaren Mercedes": "McLaren"
  "Williams Toyota": "Williams"
  "Williams Cosworth": "Williams"
  "RBR Ferrari": "Red Bull"
  "Sauber BMW": "Sauber"
  "RBR Renault": "Red Bull"
  "Lotus Cosworth": "Lotus"
  "Sauber Ferrari": "Sauber"
  "Williams Renault": "Williams"
  "Williams Mercedes": "Williams"
  "STR Renault": "Red Bull Junior Team"
  "McLaren Honda": "McLaren"
  "McLaren Renault": "McLaren"
  "Red Bull Racing Honda": "Red Bull"
  "Aston Martin Mercedes": "Aston Martin"
  "Aston Martin Aramco Mercedes": "Aston Martin"
  "AlphaTauri Honda RBPT": "Red Bull Junior Team"
  "Kick Sauber Ferrari": "Sauber"
  "RB Honda RBPT": "Red Bull Junior Team"
  "Alfa Romeo Racing Ferrari": "Sauber"
  "Alfa Romeo Ferrari": "Sauber"
  "Force India Ferrari": "Force India"
  "Force India Mercedes": "Force India"
  "Marussia Cosworth": "Marussia"
  "Marussia Ferrari": "Marussia"
  "STR Cosworth": "Red Bull Junior Team"
